server:
  port: 8081

spring:
  application:
    name: sys-server
  datasource:
    url: jdbc:mysql://47.107.119.14/blockchain?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: '000000'
    driver-class-name: com.mysql.cj.jdbc.Driver

dubbo:
  application:
    name: sys-server
  registry:
    address: 127.0.0.1:2181
    protocol: zookeeper
    check: false
  protocol:
    name: dubbo
    port: 30003
  monitor:
    protocol: register
  consumer:
    check: false
    timeout: 3000