server:
  port: 8081
  servlet:
    context-path: /sys

spring:
  profiles:
    active: dev

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  global-config:
    db-config:
      id-type: assign_id
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    jdbc-type-for-null: null
    call-setters-on-nulls: true