server:
  port: 8081

spring:
  profiles:
    active: dev

mybatis-plus:
  global-config:
    db-config:
      id-type: assign_id
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    jdbc-type-for-null: null
    call-setters-on-nulls: true