server:
  port: 8080

dubbo:
  application:
    name: test-server
  registry:
    address: 47.107.119.14:2182
    protocol: zookeeper
    check: false
  protocol:
    name: dubbo
    port: 30003
  monitor:
    protocol: register
  consumer:
    check: false
    timeout: 3000